### ISSUE TITLE
Create Documentation for setting up local environment

### ISSUE THREAD

**Issue by simransinghal** [bugmark/exchange#69]
It's easy for the newbies to start contributing to the project if we have good Readme including the steps of setting up the local environment of the project.

**Comment by simransinghal** [comment]
@andyl I want to work on this issue.

**Comment by GeorgLink** [comment]
Hi @simransinghal,

This is a great idea. We have a dated description (https://github.com/bugmark/bugmark/blob/master/notes/devenv.md). This could be a starting point for you to create detailed instructions that we can put on our README. If you run into issues, @andyl knows the answer to.

**Comment by simransinghal** [comment]
Hello @andyl @GeorgLink I send the pull request for this issue. Please give the suggestions on how I can improve it more.

**Comment by snehasi** [comment]
There is a Bugmark intern offer on this issue.
My merged PR for this issue  : https://github.com/bugmark/exchange/pull/73

**Comment by GeorgLink** [comment]
@snehasi if this issue is resolved, can you close it yourself?

**Comment by GeorgLink** [comment]
I will test the installation instructions later today and see if I can get them to work for a clean Ubuntu VM.

**Comment by andyl** [comment]
Mostly now we're cloning Linode VMs.  Instant provisioning.

**Comment by GeorgLink** [comment]
I still want to go through and test the instructions on a local machine. 

Installation instructions are important for onboarding new people. The installation is one of the first things newcomers may try and if it fails, they may not stick around.

**Comment by GeorgLink** [comment]
What is the output in step `Development Environment Provisionsing - 5. Check database status` supposed to be? `not-found` and `inactive` are intuitively not what I want - See output in below image.

![image](https://user-images.githubusercontent.com/8862021/41719170-e0571bec-7524-11e8-8cb4-f0758630c6e0.png)

**Comment by GeorgLink** [comment]
Error in step `Application Bootstrap - 1. Install ruby gem`.  - See output in below image.

![image](https://user-images.githubusercontent.com/8862021/41719299-4a7ab4ac-7525-11e8-9c7a-934e8ba76b01.png)

**Comment by GeorgLink** [comment]
I'm stopping the installation attempt, until we resolve the errors.

**Comment by snehasi** [comment]
Hi,

"Error in step Development Environment Provisionsing - 4. Provision the dev machine. - See output in below image." - This is due to your ansible configuration, I got the same error, as you can see below:

![ansible_error3](https://user-images.githubusercontent.com/22666460/41720108-db4f1342-7516-11e8-987d-6943be6854d4.png)

This error can be resolved by `updating your ansible config` to the one specified in the requirements, after successful dev env config setup, you'd get an output like the one below:
![localhostyayya](https://user-images.githubusercontent.com/22666460/41720182-1f6b85d8-7517-11e8-9543-52c752ea9135.png)

**Comment by snehasi** [comment]
"What is the output in step Development Environment Provisionsing - 5. Check database status supposed to be? not-found and inactive are intuitively not what I want - See output in below image"

This is because your development environment provisioning isn't complete, you can check the database status and see active sessions after that only, which is the sixth step.

**Comment by snehasi** [comment]
Try `sudo gem install bundler`.

**Comment by snehasi** [comment]
You can find more about troubleshooting in my detailed notes [here](https://github.com/snehasi/exchange/blob/17ce2c93e43527575ad90f160f40f8794edbe693/notes/detailed_devenv.md).

**Comment by GeorgLink** [comment]
Thanks @snehasi I can tell that you have some great knowledge of how Bugmark is setup.

>> Error in step Development Environment Provisionsing - 4. Provision the dev machine. 

> This error can be resolved by updating your ansible config to the one specified in the requirements, after successful dev env config setup, you'd get an output like the one below:

I followed the instructions step by step. 
What command exactly needs to be added to the instructions to `update ansible config` ? (I tried `sudo apt-get update` and `sudo apt-get upgrade`).

I like the idea of including 'check points' in the instructions. Checkpoints make sure that a step was completed successfully, such as checking that the ansible version is correct.

**Comment by snehasi** [comment]
From my notes:
If you see the error fatal: [localhost]: FAILED! => {"changed": false, "failed": true,"msg": "Unsupported parameter for module: path"} It's probably because your ansible version isn't compatible, try upgrading your ansible version with:

Check the version: ansible --version

To upgrade your ansible version: sudo -H pip install --upgrade ansible

If this doesn't work, try removing all the previous versions and installing again with PPA:

 ```
compgen -c | grep ansible (should not return anything)
 sudo apt-add-repository ppa:ansible/ansible
 sudo apt-get update
 sudo apt-get install ansible
```

**Comment by GeorgLink** [comment]
Thanks @snehasi 

The first option did not work (`sudo -H pip install --upgrade ansible`). 
![image](https://user-images.githubusercontent.com/8862021/41731293-a18b2600-7543-11e8-9bd4-9d83fce724fc.png)

When I run the fist line of the alternative, I do get a return, against your instructions:
![image](https://user-images.githubusercontent.com/8862021/41731333-c70e486c-7543-11e8-8629-4969568ba5d6.png)

I'm following the instructions only, because I want to make sure that someone who does not have a background in all this can setup the dev environment. 

What is the necessary step we need to add to the instructions, to make them work?

**Comment by snehasi** [comment]
@GeorgLink 

As I said you have to `remove the previous versions of ansible first`, grep is just searching for ansible and should return nothing, as a check afterwards.

**Comment by snehasi** [comment]
pip is mostly failing build these days, that's why I have also specified how to install with ppa.

**Comment by GeorgLink** [comment]
Thanks @snehasi 

> As I said you have to remove the previous versions of ansible first, grep is just searching for ansible and should return nothing, as a check afterwards.

What is the command for that?

**Comment by snehasi** [comment]
```sudo apt-get remove ansible```

**Comment by GeorgLink** [comment]
Awesome. Thank you!

**Comment by GeorgLink** [comment]
@snehasi  I appreciate your help through the install instructions. 

Is it normal, that I get yelled at (all caps) that `INFLUXDB NOT FOUND` during step `Application Bootstrap - Create databases` ?

![image](https://user-images.githubusercontent.com/8862021/41733447-7c7cbb8e-7549-11e8-88be-ceb42a37151d.png)

**Comment by snehasi** [comment]
No, that's not an error, InfluxDB is turned off for this repo, while setting up influuxDB for funderclone and intern exercises, we simply included it in the installation in ./util/code_util/cfg/_ansible/playbooks/bugmark.yml

**Comment by GeorgLink** [comment]
Awesome, thanks @snehasi 

I think, the server is up and running 👍 

Do you know how to make the server accessible for a Windows host? Neither of the IP addresses work.

![image](https://user-images.githubusercontent.com/8862021/41733772-8dec06bc-754a-11e8-9af3-71895ce25c8d.png)

**Comment by snehasi** [comment]
You can check out this link, just in case: https://serverfault.com/questions/136715/how-do-i-access-a-web-server-on-a-virtualbox-from-the-host-machine
Great!

**Comment by GeorgLink** [comment]
Thanks again @snehasi for all your help today. 

Turns out that the installation notes were okay, it was an error in one of the scripts.

I created a pull request with the fix and minor changes to the devenv.md notes. #82

**Comment by GeorgLink** [comment]
This issue will be closed automatically, when pull request #82 is merged.

**Comment by snehasi** [comment]
Okay, this is great. Nice fix!

**Comment by GeorgLink** [comment]
#85 looks promising.
